SELECT * FROM STTM_SOLUTIONS.SEMANTIC_MAPPING.V_BEST_MATCHES
;--WHERE TARGET_TABLE = 'PERSON' AND TARGET_COLUMN = 'PERSON_ID';

-- Intial Target Matches
-- When best fit makes no sense find alternatives
-- Review alternative matches for specific columns
SELECT 
    TARGET_COLUMN,
    SOURCE_COLUMN,
    CONFIDENCE_SCORE,
    MATCH_RANK,
    TRANSFORMATION_SQL
FROM SEMANTIC_MAPPING.V_ALL_MATCH_CANDIDATES
WHERE TARGET_TABLE = 'PERSON' AND TARGET_COLUMN = 'PERSON_ID'
ORDER BY MATCH_RANK;