USE DATABASE STAR_DEV;
USE SCHEMA SEMANTIC_MAPPING;

DROP TABLE IF EXISTS STAR_DEV.SEMANTIC_MAPPING.COLUMN_DISTRIBUTIONS;
CREATE OR REPLACE TABLE STAR_DEV.SEMANTIC_MAPPING.COLUMN_DISTRIBUTIONS(
    TABLE_NAME          VARCHAR(255),
    COLUMN_NAME         VARCHAR(255),
    DATA_TYPE           VARCHAR(50),
    COLUMN_CLASS        VARCHAR(20),     -- 'NUMERIC' or 'CATEGORICAL'
    PRIMARY_ROLE        VARCHAR(20),     -- 'FLAG', 'ID', 'MEASURE', or 'CODE'
    SECONDARY_ROLES     ARRAY,           -- Stores ['SURROGATE_KEY', 'ENUM', etc.]
    TOP_VALUES          ARRAY,           -- Stores JSON objects of top 10 values/pcts
    ENTROPY_SCORE       FLOAT,
    SKEWNESS            FLOAT,
    MODAL_VALUE_PCT     FLOAT,
    MEAN_VAL            FLOAT,
    STDDEV_VAL          FLOAT,
    MIN_VAL             FLOAT,
    MAX_VAL             FLOAT,
    UNIT_COLUMN         VARCHAR(255),
    DENSITY             VARCHAR(100),    -- e.g., '10.5 per unit'
    PROFILED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE SP_TABLE_DISTRIBUTION(
    PROFILE_DB VARCHAR,
    PROFILE_SCHEMA VARCHAR,
    PROFILE_TABLE VARCHAR,
    UNIT_COLUMN VARCHAR,
    DISTRIBUTION_TABLE VARCHAR DEFAULT 'STAR_DEV.SEMANTIC_MAPPING.COLUMN_DISTRIBUTIONS'
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_unpivot_list STRING;
    v_unpivot_cast STRING;
    v_sql STRING;
    info_schema_path STRING := PROFILE_DB || '.INFORMATION_SCHEMA.COLUMNS';
    v_error_msg STRING;
    v_unit_col_clause STRING;
    v_density_clause STRING;
BEGIN
    -- Validate table exists
    LET v_table_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO :v_table_count
        FROM IDENTIFIER(:info_schema_path)
        WHERE table_schema = :PROFILE_SCHEMA
          AND table_name = :PROFILE_TABLE;
        
        IF (v_table_count = 0) THEN
            RETURN 'ERROR: Table ' || PROFILE_DB || '.' || PROFILE_SCHEMA || '.' || PROFILE_TABLE || ' does not exist';
        END IF;
    EXCEPTION
        WHEN OTHER THEN
            RETURN 'ERROR: Unable to access table metadata for ' || PROFILE_DB || '.' || PROFILE_SCHEMA || '.' || PROFILE_TABLE || ' - ' || SQLERRM;
    END;
    
    -- Validate unit column exists if provided
    IF (UNIT_COLUMN = '' OR UNIT_COLUMN IS NULL) THEN
        -- Unit column not specified - set clauses for NULL density
        v_unit_col_clause := '''unspecified''';
        v_density_clause := 'NULL';
        v_error_msg := 'NOTE: Unit column not specified - density metric will be NULL. ';
    ELSE
        -- Unit column specified - validate it exists
        LET v_col_count NUMBER;
        BEGIN
            SELECT COUNT(*) INTO :v_col_count
            FROM IDENTIFIER(:info_schema_path)
            WHERE table_schema = :PROFILE_SCHEMA
              AND table_name = :PROFILE_TABLE
              AND column_name = :UNIT_COLUMN;
            
            IF (v_col_count = 0) THEN
                RETURN 'ERROR: Temporal column ' || UNIT_COLUMN || ' does not exist in table ' || PROFILE_TABLE;
            END IF;
        EXCEPTION
            WHEN OTHER THEN
                RETURN 'ERROR: Unable to validate temporal column - ' || SQLERRM;
        END;
        
        -- Set clauses for density calculation
        v_unit_col_clause := '''' || UNIT_COLUMN || '''';
        v_density_clause := 'ROUND(COUNT(*)/NULLIF(unt.units,0),2)::VARCHAR || '' per unit''';
    END IF;
    
    -- Build unpivot column list
    BEGIN
        IF (UNIT_COLUMN = '' OR UNIT_COLUMN IS NULL) THEN
            -- No unit column to exclude
            SELECT
                LISTAGG(
                    column_name || '::VARCHAR AS ' || column_name || '_V',
                    ',\n            '
                ) WITHIN GROUP (ORDER BY ordinal_position),
                LISTAGG(column_name || '_V', ',\n            ') WITHIN GROUP (ORDER BY ordinal_position)
            INTO :v_unpivot_cast, :v_unpivot_list
            FROM IDENTIFIER(:info_schema_path)
            WHERE table_schema = :PROFILE_SCHEMA
              AND table_name = :PROFILE_TABLE
              AND data_type NOT IN ('VARIANT', 'ARRAY', 'OBJECT')
              AND column_name NOT IN ('ETL_CREATED_DATE', 'ETL_UPDATED_DATE', 'ETL_CREATED_BY', 'ETL_UPDATED_BY');
        ELSE
            -- Exclude the unit column
            SELECT
                LISTAGG(
                    column_name || '::VARCHAR AS ' || column_name || '_V',
                    ',\n            '
                ) WITHIN GROUP (ORDER BY ordinal_position),
                LISTAGG(column_name || '_V', ',\n            ') WITHIN GROUP (ORDER BY ordinal_position)
            INTO :v_unpivot_cast, :v_unpivot_list
            FROM IDENTIFIER(:info_schema_path)
            WHERE table_schema = :PROFILE_SCHEMA
              AND table_name = :PROFILE_TABLE
              AND data_type NOT IN ('VARIANT', 'ARRAY', 'OBJECT')
              AND column_name <> :UNIT_COLUMN
              AND column_name NOT IN ('ETL_CREATED_DATE', 'ETL_UPDATED_DATE', 'ETL_CREATED_BY', 'ETL_UPDATED_BY');
        END IF;
        
        IF (v_unpivot_list IS NULL OR v_unpivot_list = '') THEN
            RETURN 'ERROR: No valid columns found to profile in table ' || PROFILE_TABLE;
        END IF;
    EXCEPTION
        WHEN OTHER THEN
            RETURN 'ERROR: Failed to build column list - ' || SQLERRM;
    END;
    
    -- Build and execute main profiler query
    BEGIN
        v_sql := '
INSERT INTO ' || DISTRIBUTION_TABLE || '   
WITH column_metadata AS (
    SELECT
        column_name,
        data_type,
        CASE
            WHEN data_type IN (
                ''NUMBER'', ''DECIMAL'', ''NUMERIC'',
                ''FLOAT'', ''FLOAT4'', ''FLOAT8'',
                ''DOUBLE'', ''DOUBLE PRECISION'',
                ''INT'', ''INTEGER'', ''BIGINT'',
                ''SMALLINT'', ''TINYINT'', ''BYTEINT''
            ) THEN ''NUMERIC''
            ELSE ''CATEGORICAL''
        END AS column_class
    FROM ' || PROFILE_DB || '.INFORMATION_SCHEMA.COLUMNS 
    WHERE table_schema = ''' || PROFILE_SCHEMA || '''
      AND table_name   = ''' || PROFILE_TABLE || '''
),

base_projected AS (
    SELECT
        t.*,
        ' || v_unpivot_cast || '
    FROM ' || PROFILE_DB || '.' || PROFILE_SCHEMA || '.' || PROFILE_TABLE || ' AS t
),

unpivoted AS (
    SELECT
        REPLACE(column_name, ''_V'', '''') AS column_name,
        value
    FROM base_projected
    UNPIVOT (
        value FOR column_name IN (
            ' || v_unpivot_list || '
        )
    )
),

unpivoted_with_type AS (
    SELECT
        u.column_name,
        cm.column_class,
        u.value::VARCHAR AS val,
        CASE
            WHEN cm.column_class = ''NUMERIC'' THEN TRY_TO_NUMBER(u.value)
            ELSE NULL
        END AS num_val,
        ' || v_unit_col_clause || ' AS temporal_value
    FROM unpivoted u
    JOIN column_metadata cm
      ON u.column_name = cm.column_name
    WHERE u.value IS NOT NULL
),

value_counts AS (
    SELECT column_name, column_class, val, COUNT(*) AS cnt
    FROM unpivoted_with_type
    GROUP BY column_name, column_class, val
),

column_totals AS (
    SELECT column_name, SUM(cnt) AS total_cnt
    FROM value_counts
    GROUP BY column_name
),

ranked AS (
   SELECT
        vc.column_name,
        vc.column_class,
        vc.val,
        vc.cnt,
        vc.cnt / NULLIF(ct.total_cnt, 0) AS pct,
        ROW_NUMBER() OVER (
            PARTITION BY vc.column_name
            ORDER BY vc.cnt DESC
        ) AS rn
    FROM value_counts vc
    JOIN column_totals ct ON vc.column_name = ct.column_name
),

top_values AS (
    SELECT
        column_name,
        ARRAY_AGG(
            OBJECT_CONSTRUCT(
                ''value'', val,
                ''pct'', ROUND(pct, 6)
            )
        ) WITHIN GROUP (ORDER BY pct DESC) AS top_values,
        MAX(pct) AS modal_value_pct
    FROM ranked
    WHERE rn <= 10
    GROUP BY column_name
),

entropy AS (
    SELECT column_name, -SUM(CASE WHEN pct > 0 THEN pct * LOG(2,pct) ELSE 0 END) AS entropy_score
    FROM ranked
    GROUP BY column_name
),

numeric_stats AS (
    SELECT column_name, COUNT(num_val) AS n, AVG(num_val) AS mean_val,
           STDDEV_SAMP(num_val) AS stddev_val, MIN(num_val) AS min_val, MAX(num_val) AS max_val
    FROM unpivoted_with_type
    WHERE column_class = ''NUMERIC'' AND num_val IS NOT NULL
    GROUP BY column_name
),

categorical_skew AS (
    SELECT column_name, MAX(cnt)::FLOAT / NULLIF(AVG(cnt),0) AS skewness
    FROM value_counts
    WHERE column_class = ''CATEGORICAL''
    GROUP BY column_name
),

numeric_skew AS (
    SELECT u.column_name,
           CASE WHEN ns.stddev_val > 0 AND ns.n > 2 THEN
                SUM(POWER((u.num_val - ns.mean_val)/NULLIF(ns.stddev_val,0),3)) * ns.n / NULLIF((ns.n-1)*(ns.n-2), 0)
           ELSE NULL END AS skewness
    FROM unpivoted_with_type u
    JOIN numeric_stats ns ON u.column_name = ns.column_name
    WHERE u.column_class = ''NUMERIC'' AND u.num_val IS NOT NULL
    GROUP BY u.column_name, ns.mean_val, ns.stddev_val, ns.n
),

unit_density AS (
    SELECT u.column_name, ' || v_unit_col_clause || ' as UNIT_COL, ' || v_density_clause || ' AS density
    FROM unpivoted_with_type u' ||
    CASE 
        WHEN (UNIT_COLUMN = '' OR UNIT_COLUMN IS NULL) THEN '
    GROUP BY u.column_name'
        ELSE '
    CROSS JOIN (SELECT COUNT(DISTINCT ' || UNIT_COLUMN || ') AS units FROM ' || PROFILE_DB || '.' || PROFILE_SCHEMA || '.' || PROFILE_TABLE || ') unt
    WHERE unt.units IS NOT NULL
    GROUP BY u.column_name, unt.units'
    END || '
),

final_metrics AS (
    SELECT tv.column_name, cm.data_type, cm.column_class, tv.top_values, e.entropy_score,
           COALESCE(ns2.skewness, cs.skewness) AS skewness,
           tv.modal_value_pct, ud.unit_col, ud.density, ns.mean_val, ns.stddev_val, ns.min_val, ns.max_val
    FROM top_values tv
    JOIN column_metadata cm ON tv.column_name = cm.column_name
    JOIN entropy e ON tv.column_name = e.column_name
    LEFT JOIN categorical_skew cs ON tv.column_name = cs.column_name
    LEFT JOIN numeric_skew ns2 ON tv.column_name = ns2.column_name
    LEFT JOIN numeric_stats ns ON tv.column_name = ns.column_name
    LEFT JOIN unit_density ud ON tv.column_name = ud.column_name
),

column_roles AS (
    SELECT fm.*, CASE
        WHEN fm.column_class = ''NUMERIC'' AND fm.min_val IN (0,1) AND fm.max_val IN (0,1) AND fm.modal_value_pct > 0.8 THEN ''FLAG''
        WHEN fm.column_name ILIKE ''%_ID'' OR fm.column_name ILIKE ''%_KEY'' THEN ''ID''
        WHEN fm.column_class = ''NUMERIC'' THEN ''MEASURE''
        ELSE ''CODE''
    END AS primary_role
    FROM final_metrics fm
),

secondary_roles AS (
    SELECT cr.*, ARRAY_COMPACT(ARRAY_CONSTRUCT(
        IFF(cr.primary_role=''ID'' AND cr.column_name ILIKE ''%_KEY'',''SURROGATE_KEY'',NULL),
        IFF(cr.primary_role=''ID'' AND cr.column_name ILIKE ''%_ID'',''FOREIGN_KEY'',NULL),
        IFF(cr.primary_role=''CODE'' AND cr.entropy_score<3,''ENUM'',NULL)
    )) AS secondary_roles
    FROM column_roles cr
)

SELECT ''' || PROFILE_TABLE || ''' AS table_name, column_name, data_type, column_class, primary_role,
       secondary_roles, top_values, entropy_score, skewness, modal_value_pct, mean_val, stddev_val,
       min_val, max_val, unit_col, density, CURRENT_TIMESTAMP
FROM secondary_roles;
';

        EXECUTE IMMEDIATE v_sql;
        RETURN COALESCE(v_error_msg, '') || 'STM profiler completed for table ' || PROFILE_TABLE;
        
    EXCEPTION
        WHEN OTHER THEN
            RETURN 'ERROR: Failed to execute profiler query - ' || SQLERRM;
    END;
END;
$$;

-----
-- DIM_MODEL PROFILING
----
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_APPOINTMENT_ACTIVITY','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_APPOINTMENT_STATUS','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_BILLING_ADJUSTMENT','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_BILLING_PAYMENT','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_BUSINESS_UNIT','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_COA_DEPARTMENT','DEPARTMENT_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_COA_GL_ACCOUNT','ACCOUNT_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_COA_GL_PERIOD','PERIOD_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_COA_SERVICE_LINE','SERVICE_LINE_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_COA_SUBSIDIARY','SUBSIDIARY_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_CPTCODE','CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_DATE','DIM_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_EEO_ATTRIBUTE','DIM_EEO_ATTRIBUTE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_EMPLOYEE','CLIENT_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_ESS_ATTRIBUTE','ESS_ACCESS_PROFILE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_FINANCE_LOCATION','LOCATION_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_INSURANCE','INSURANCE_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_INSURANCE_PROVIDER','INSURANCE_PROVIDER_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_LOCATION','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_OPERATIONAL_CENTER','OPERATIONAL_CENTER_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_ORGANIZATION','DIM_ORGANIZATION_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_PATIENT','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_PAYMENT_METHOD','METHOD');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_PAY_STRUCTURE','DOL_STATUS');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_PLACE_OF_SERVICE','SERVICE_LINE_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_POSITION','POSITION_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_POSITION_CATEGORY','POSITION_CATEGORY_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_PROVIDER','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_RECALL_STATUS','RECALL_STATUS_CODE');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_RECALL_TYPE','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_REFERRING_PROVIDER','ORGANIZATION_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_USER','USER_ID');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','DIM_WORK_LOCATION','WORK_LOCATION');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_APPOINTMENT','DIM_APPOINTMENT_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_APPOINTMENT_WITH_ETL_DATES','DIM_APPOINTMENT_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_ADJUSTMENTS','DIM_SERVICE_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_CHARGES','DIM_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_CHARGES_WITH_ETL_DATES','DIM_SERVICE_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_LEDGER','DIM_SERVICE_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_LEDGER_W_ETL_DATES','DIM_SERVICE_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_PAYMENTS','DIM_SERVICE_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_BILLING_REFUNDS','DIM_SERVICE_DATE_KEY');
-- **NOT RUN** CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_EMPLOYEE_HISTORY','DIM_EMPLOYEE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_ENCOUNTER_PROCEDURE','DIM_DATE_KEY');
CALL SP_TABLE_DISTRIBUTION('STAR','DIM_MODEL','FACT_RECALL','DIM_RECALL_DATE_KEY');

CREATE TABLE STAR_DEV.SEMANTIC_MAPPING.STAR_DIM_MODEL_COLUMN_DISTRIBUTIONS AS
SELECT * FROM STAR_DEV.SEMANTIC_MAPPING.COLUMN_DISTRIBUTIONS;

SELECT TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME
FROM STAR.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='GGASTRO'
  AND TABLE_TYPE='BASE TABLE'
  AND STARTSWITH(TABLE_NAME,'STG_')

-----
-- GGASTRO PROFILING
----
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGETRANSACTIONCOLLECTIONADJUSTMENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULEPRICEPERPROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FWK_USER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_STAFF','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGINSURANCECATEGORY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPATIENTAUTHORIZATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_DHAT_DATA_LOAD_TEST_2021','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RECALLTYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_EDW_PHONE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERFACETESTRESULT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_MEDICALHISTORYREVIEW','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RESOURCEPERAPPOINTMENT1','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_APPOINTMENTSTATUS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCLAIMEVENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_LOCATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PRESCRIPTIONINBOUNDQUEUE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGETRANSACTION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCLAIM','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGENCOUNTEREVENTTASKRECIPIENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPATIENTLEDGER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INSURANCEPROVIDERPLACEOFSERVICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_L_LOCATION_PEORIA','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RECALLEVENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICETYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULEPRICEPERINSURANCEPROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_CODINGADVISOR2021','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_DHAT_DATA_LOAD_TEST_JAN_2021','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_GIQUICEXPORT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERFACERESULT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PLACEOFSERVICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_REFERRINGPHYSICIANIDENTIFICATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICETIMEMARKER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TASKTYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPROCEDURECODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_APPOINTMENTSET','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPROCEDURECODEMODIFIER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILLPROCEDURE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_COUNTRY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FWK_LIST','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TDDC_CHANGEREPORT_1','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGEMODIFIER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_CPTCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FINDING','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INSURANCEPROVIDERCPTCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PROCEDUREINTERRUPTED','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RAMNEWSTORAGE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICESTAFF','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TASKNOTES','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_OUTOFOFFICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PATIENTTEST','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TASK','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_APPOINTMENTSTATUSHISTORY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGBUSINESSUNITPERLOCATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGENCOUNTERDIAGNOSIS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGENCOUNTERDIAGNOSISPERCHARGE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPAYMENTADJUSTMENTREFUND','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_CODINGADVISORMDMTIMEMODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_IMAGINGSERVICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERFACERESULTPATHOLOGY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PATIENTILLNESS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICETIMEMARKERTYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCOSTCENTER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILLDIAGNOSISPERPROCEDURE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILLPROCEDUREMODIFIER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FWK_AUDITLOG','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_ICD10CODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RAM','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RVU','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FWK_ROLE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PRESCRIPTION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TDDC_LOAD','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TEST08272024','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PHARMACY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PROVIDERPERPATIENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGETRANSACTIONADJUSTMENTDETAIL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGENCOUNTEREVENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGINSURANCEDENIALCATEGORY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BLOODPRESSURE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_EDW_RAPT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TESTEESTRESTSETTEST','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULEPRICEPERPROCEDURECODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILLIMPORTPERSONRACE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BOD_REGIONALMAP','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERFACETEST','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_MATILLION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULEPRICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TEST_CONNECTION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_APPOINTMENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGADJUSTMENTCODETYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGINSURANCEREASONCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_CLAIM_RESPONSIBLE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_L_PHYSICIAN_FF','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGANESTHESIASERVICETYPE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGBUSINESSUNIT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCLAIMSTATUS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGSUPERBILLDIAGNOSIS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_EDW_COUNTRY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_EDW_EMAIL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_IGG_PEORIA_ENCOUNTERS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERVENTION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PATIENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PATIENTDIAGNOSIS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PHONE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RESOURCEPERAPPOINTMENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_SERVICEPROCEDUREINDICATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_STAFFIDENTIFICATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGENCOUNTER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FWK_USERDETAIL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RVUHISTORY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_MEDICATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_ADH_HISTORICAL_LOAD','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGBATCH','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCLAIMSNAPSHOT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGTYPEOFSERVICE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PHYSICALMEASUREMENT','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RESOURCEPERAPPOINTMENTHOLD','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCHARGETRANSACTIONADJUSTMENTDETAIL_BAD','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGCOSTCENTERASSIGNEDTOPROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULEPRICEPERLOCATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPAYMENTCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INSURANCE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_ORDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_POSTING_AND_ EDITRULES','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_REFERRINGPHYSICIAN','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_USAADDRESS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_EMAIL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PRESCRIPTIONSAMPLE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_VITALSIGNS','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PATIENTVIEW','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RVU_CPTCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_ACTIVITY','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_ANALYTICS_PROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_AUDIT_USER_ROLE_CHANGES','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGADJUSTMENTCODE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGELIGIBILITYFAILUREREASON','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGFEESCHEDULE','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGPATIENTBILLINGINFORMATION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_GUARANTOR','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_RECALL','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INSURANCEPROVIDER','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_PERSON','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_TESTEESTRESTSET','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_FINDINGDESCRIPTION','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_IGG_PEORIA_CHARGES','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_INTERFACEMAPPING','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_BILLINGINSURANCEPAYERGROUP','');
CALL SP_TABLE_DISTRIBUTION('STAR','GGASTRO','STG_LIMITATIONCOMPLICATION','');
